config/routes.rb
Rails.application.routes.draw do
  resources :designs

  resources :categories do
    resources :recipes, except: %i[show]
    resources :cakemodels, except: %i[show]
    collection do
      get :recipes
    end
  end
  resources :recipes, only: %i[show] do
    resources :reviews, only: %i[create edit update destroy]
  end
  resources :cakemodels, only: %i[show] do
    resources :model_images, only: %i[new create destroy]
    resources :model_components, only: %i[new create destroy]
    resources :reviews, only: %i[create edit update destroy]
  end

  resources :model_components, only: %i[new create destroy]

  resources :features

  resources :items

  resource :cart, only: %i[show]

  devise_for :users
  root to: 'pages#home'
  get 'preturi', to: 'recipes#update_prices'
  patch 'preturi', to: 'recipes#bulk_update_prices'
  get 'cautare-retete', to: 'recipes#search'
  get 'how_to_order', to: 'pages#how_to_order'
  get 'about', to: 'pages#about'
  get 'valori-nutritionale', to: 'pages#valori_nutritionale'
  get 'gdpr', to: 'pages#gdpr', as: :gdpr
  get 'contul-meu', to: 'accounts#show', as: :account
  get 'dashboard',  to: 'pages#admin_dashboard'
  get 'dashboard/designs', to: 'designs#index'
  get 'dashboard/features', to: 'features#index'

  namespace :dashboard do
    resources :orders, only: %i[index show update destroy] do
      post :resend_emails, on: :member
    end
    resources :recipes, only: :index
    resources :cakemodels, only: %i[index create update]
    resources :delivery_dates, only: :index do
      collection do
        post :toggle
        post :block_range
      end
    end
    resources :users, only: %i[index edit update] do
      member do
        patch :toggle_admin
      end
    end

    resources :admin_users, controller: 'admin_users' do
      member do
        patch :toggle_admin
      end
    end

    resources :audit_logs, only: %i[index show] do
      collection do
        get :statistics
        get :export
      end
    end

    get 'analytics', to: 'analytics#index', as: 'analytics'
    
    namespace :design do
      get 'site_settings', to: 'site_settings#index'
      patch 'site_settings', to: 'site_settings#update'
      post 'site_settings/upload_hero_image', to: 'site_settings#upload_hero_image'
      delete 'site_settings/remove_hero_image', to: 'site_settings#remove_hero_image'
      post 'site_settings/templates', to: 'site_settings#create_template', as: 'create_site_setting_template'
      post 'site_settings/templates/:id/apply', to: 'site_settings#apply_template', as: 'apply_site_setting_template'
      delete 'site_settings/templates/:id', to: 'site_settings#destroy_template', as: 'destroy_site_setting_template'
    end
  end

  namespace :shop do
    resource :cart, only: :show
    resources :cart_items, only: %i[create update destroy]
    post 'checkout', to: 'checkout#create'
    get 'checkout/success', to: 'checkout#success'
    get 'checkout/cancel', to: 'checkout#cancel'
    get 'guest_confirmation/:id/:token', to: 'checkout#guest_confirmation', as: :guest_confirmation
  end

  # Catch-all route for 404 errors - must be last, but exclude Rails internal routes
  get '*any', to: 'errors#not_found', constraints: lambda { |req|
    req.path.exclude?('rails/active_storage') && 
    req.path.exclude?('rails/conductor')
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/cakemodels_controller.rb
class CakemodelsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index]
  before_action :set_category, only: %i[new create edit update destroy index show]
  before_action :set_cakemodel, only: %i[show edit update destroy]
  before_action :load_form_dependencies, only: %i[new create edit update]

  def new
    @cakemodel = authorize Cakemodel.new
    @page_title = 'Sugestie de prezentare nouă || Cofetăria Irina Bacău'
  end

  def create
    @cakemodel = authorize Cakemodel.new(cakemodel_params)
    @cakemodel.category = @category

    selected_recipe = @torturi_recipes.find_by(id: @cakemodel.initial_recipe_id)
    unless selected_recipe
      @cakemodel.errors.add(:initial_recipe_id, 'trebuie sa fie din categoria Torturi')
      flash.now.alert = @cakemodel.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
      return
    end

    Cakemodel.transaction do
      @cakemodel.save!
      @cakemodel.model_components.create!(
        recipe: selected_recipe,
        weight: initial_component_weight(@cakemodel)
      )
    end

    redirect_to category_cakemodels_path(@category)
  rescue ActiveRecord::RecordInvalid => e
    flash.now.alert = if @cakemodel&.errors&.any?
                        @cakemodel.errors.full_messages.to_sentence
                      else
                        e.message
                      end
    render :new, status: :unprocessable_entity
  end

  def index
    @cakemodels = policy_scope(Cakemodel).where(category_id: @category).order(:id)
    @page_title = "Modele de #{@category.name.downcase} || Cofetăria Irina - Bacau"
  end

  def show
    @review = Review.new
    @reviews = @cakemodel.reviews.all.order('id DESC')
    @category = @cakemodel.category
    @design = @cakemodel.design
    @page_title = "Detalii și recenzii pentru #{@cakemodel.name} "
    @cakemodels = policy_scope(Cakemodel).where(category_id: @category).order('id ASC')
    @model_image = ModelImage.new
    @model_component = ModelComponent.new
    @recipes = torturi_recipes_scope
    @torturi_recipes = @recipes
  end

  def edit
    @page_title = 'Modifică sugestie de prezentare || Cofetăria Irina Bacău'
  end

  def update
    selected_recipe = selected_torturi_recipe_from_params
    if cakemodel_params[:initial_recipe_id].present? && selected_recipe.nil?
      @cakemodel.errors.add(:initial_recipe_id, 'trebuie sa fie din categoria Torturi')
      flash.now.alert = @cakemodel.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
      return
    end

    Cakemodel.transaction do
      @cakemodel.update!(cakemodel_params.except(:initial_recipe_id))
      sync_initial_recipe_component!(@cakemodel, selected_recipe) if selected_recipe.present?
    end

    redirect_to category_cakemodels_path(@category)
  rescue ActiveRecord::RecordInvalid
    flash.now.alert = @cakemodel.errors.full_messages.to_sentence
    render :edit, status: :unprocessable_entity
  end

  def destroy
    @cakemodel.destroy
    redirect_to category_cakemodels_path(@category)
  end

  private

  def cakemodel_params
    params.require(:cakemodel).permit(
      :name,
      :photo,
      :design_id,
      :content,
      :featured_for_quick_order,
      :weight,
      :price_per_kg,
      :price_per_piece,
      :final_price,
      :available_online,
      :available_for_delivery,
      :display_order,
      :initial_recipe_id
    )
  end

  def set_category
    @category = Category.find_by(slug: params[:category_id])
  end

  def set_cakemodel
    @cakemodel = authorize Cakemodel.find_by(slug: params[:id])
  end

  def load_form_dependencies
    @designs = Design.all
    @torturi_recipes = torturi_recipes_scope
    @recipe_price_map = build_recipe_price_map(@torturi_recipes)
    @design_price_map = build_design_price_map(@designs)
  end

  def initial_component_weight(cakemodel)
    grams = cakemodel.weight.to_f
    return 0.0 if grams <= 0

    (grams / 1000.0).round(3)
  end

  def torturi_recipes_scope
    torturi_category = Category.where("LOWER(TRIM(slug)) = :name OR LOWER(TRIM(name)) = :name", name: 'torturi').first
    return Recipe.none unless torturi_category

    Recipe.where(category_id: torturi_category.id).order(:name)
  end

  def build_recipe_price_map(recipes)
    recipes.each_with_object({}) do |recipe, map|
      map[recipe.id] = money_to_float(recipe.price)
    end
  end

  def build_design_price_map(designs)
    designs.each_with_object({}) do |design, map|
      map[design.id] = money_to_float(design.price)
    end
  end

  def money_to_float(value)
    return 0.0 if value.blank?
    return value.to_d.to_f.round(2) if value.respond_to?(:to_d)

    value.to_f.round(2)
  rescue StandardError
    0.0
  end

  def selected_torturi_recipe_from_params
    selected_id = cakemodel_params[:initial_recipe_id].presence
    return nil if selected_id.blank?

    torturi_recipes_scope.find_by(id: selected_id)
  end

  def sync_initial_recipe_component!(cakemodel, recipe)
    component = cakemodel.model_components.order(:id).first || cakemodel.model_components.new
    component.recipe = recipe

    if component.new_record? || component.weight.blank? || component.weight.to_f <= 0
      component.weight = initial_component_weight(cakemodel)
    end

    component.save! if component.changed?
  end
end

app/controllers/dashboard/admin_users_controller.rb
class Dashboard::AdminUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  before_action :set_user, only: %i[show edit update destroy toggle_admin]

  def index
    @sort = params[:sort].presence_in(%w[email created_at role]) || "created_at"
    @direction = params[:direction].presence_in(%w[asc desc]) || "desc"

    base_scope = policy_scope(User)

    @users =
      case @sort
      when "email"
        base_scope.order(email: @direction)
      when "role"
        # admins first, then by email
        base_scope.order(admin: :desc, email: @direction)
      else
        base_scope.order(created_at: @direction)
      end
  end

  def show
    authorize @user
  end

  def new
    @user = User.new
    authorize @user
  end

  def create
    @user = User.new(user_params)
    authorize @user
    if @user.save
      redirect_to dashboard_admin_user_path(@user), notice: 'Utilizator creat cu succes.'
    else
      render :new
    end
  end

  def edit
    authorize @user
  end

  def update
    authorize @user
    if @user.update(user_params)
      redirect_to dashboard_admin_user_path(@user), notice: 'Utilizator actualizat cu succes.'
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    if @user == current_user
      redirect_back fallback_location: dashboard_admin_users_path, alert: 'Nu îți poți șterge propriul cont.'
      return
    end

    @user.destroy
    redirect_to dashboard_admin_users_path, notice: 'Utilizator șters.'
  end

  def toggle_admin
    authorize @user, :toggle_admin?

    if @user == current_user
      redirect_back fallback_location: dashboard_admin_users_path, alert: 'Nu poți modifica propriul rol.'
      return
    end

    @user.update(admin: !@user.admin)
    message = @user.admin? ? 'Utilizator promovat la administrator.' : 'Permisiuni de administrator retrase.'
    redirect_back fallback_location: dashboard_admin_users_path, notice: message
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    raise Pundit::NotAuthorizedError unless current_user&.admin?
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :admin)
  end
end

app/controllers/dashboard/analytics_controller.rb
class Dashboard::AnalyticsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin
  skip_after_action :verify_policy_scoped

  def index
    authorize :analytics, :index?
    @analytics = Dashboard::AnalyticsReport.new(params: params.to_unsafe_h).call
  end

  private

  def require_admin
    redirect_to root_path, alert: 'Nu ai permisiunea necesară.' unless current_user&.admin?
  end
end

app/controllers/dashboard/design/hero_sections_controller.rb
module Dashboard
  module Design
    class HeroSectionsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_hero_section
      before_action :authorize_hero_section

      def show
        redirect_to edit_dashboard_design_hero_section_path
      end

      def edit
        @page_title = 'Editare Hero Section ・ Cofetăria Irina'
        @page_main_title = 'Editare Hero Section'
      end

      def update
        if @hero_section.update(hero_section_params)
          redirect_to edit_dashboard_design_hero_section_path, notice: 'Hero section actualizat cu succes.'
        else
          render :edit, status: :unprocessable_entity
        end
      end

      private

      def set_hero_section
        @hero_section = HeroSection.first_or_create!(
          title: 'Deserturi proaspete',
          subtitle: 'în fiecare zi'
        )
      end

      def authorize_hero_section
        authorize @hero_section
      end

      def hero_section_params
        params.require(:hero_section).permit(:title, :subtitle, :background_image, :main_image)
      end
    end
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :require_admin

  def index
    @users = policy_scope(User).order(created_at: :desc).limit(200)
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      redirect_to dashboard_path(anchor: 'users-admin'), notice: 'Utilizator actualizat cu succes.'
    else
      render :edit
    end
  end

  def toggle_admin
    @user = User.find(params[:id])
    authorize @user, :toggle_admin?
    # prevent toggling own admin flag accidentally
    if @user == current_user
      redirect_back fallback_location: dashboard_path(anchor: 'users-admin'), alert: 'Nu poți modifica propriul rol.'
      return
    end

    @user.update(admin: !@user.admin)
    message = @user.admin? ? 'Utilizator promovat la administrator.' : 'Permisiuni de administrator retrase.'
    redirect_back fallback_location: dashboard_path(anchor: 'users-admin'), notice: message
  end

  private

  def require_admin
    raise Pundit::NotAuthorizedError unless current_user&.admin?
  end

  def user_params
    params.require(:user).permit(:email, :admin)
  end
end

app/helpers/dashboard/audit_logs_helper.rb
module Dashboard::AuditLogsHelper
  ACTION_VARIANTS = {
    'create' => 'success',
    'update' => 'primary',
    'destroy' => 'danger',
    'login' => 'info',
    'logout' => 'secondary',
    'failed_login' => 'warning'
  }.freeze

  ACTION_ICONS = {
    'create' => 'fa-plus',
    'update' => 'fa-pen',
    'destroy' => 'fa-trash',
    'login' => 'fa-right-to-bracket',
    'logout' => 'fa-right-from-bracket',
    'failed_login' => 'fa-triangle-exclamation'
  }.freeze

  def audit_action_variant(action)
    ACTION_VARIANTS.fetch(action.to_s, 'secondary')
  end

  def audit_action_icon(action)
    ACTION_ICONS.fetch(action.to_s, 'fa-circle')
  end
end

app/helpers/dashboard/orders_helper.rb
module Dashboard
  module OrdersHelper
    ORDERED_STATUSES = %w[no_status seen in_production ready delivered canceled refunded].freeze

    def order_status_badge(order)
      content_tag(:span, order.status_label, class: "badge bg-#{order.status_badge_variant}")
    end

    def order_status_options
      Cart::STATUSES.values.map do |value|
        [Cart::STATUS_LABELS[value] || value.titleize, value]
      end
    end

    def format_order_total(order)
      order.total_money.format
    end

    def format_order_quantity(order)
      quantity = order.total_quantity
      quantity == quantity.to_i ? quantity.to_i : number_with_precision(quantity, precision: 2)
    end

    def render_contact_detail(label, value)
      content_tag(:p, class: 'mb-1') do
        concat content_tag(:span, "#{label}:", class: 'text-muted me-1')
        concat(value.presence || '-')
      end
    end

    def human_delivery_method(order)
      case order.method_of_delivery
      when 'delivery'
        'Livrare'
      when 'pickup'
        'Ridicare personală'
      else
        '-'
      end
    end

    def order_status_button_class(order, status_value)
      base_classes = %w[btn btn-sm px-2 py-0]

      current_index = ORDERED_STATUSES.index(order.status.to_s) || -1
      target_index = ORDERED_STATUSES.index(status_value.to_s)

      color_class = if target_index.nil?
                      'btn-outline-secondary'
                    elsif target_index < current_index
                      'btn-outline-success' # passed
                    elsif target_index > current_index
                      'btn-outline-danger'  # future
                    else
                      'btn-outline-warning' # current (should be skipped, defensive)
                    end

      (base_classes + [color_class]).join(' ')
    end
  end
end

app/views/dashboard/cakemodels/_cakemodel.html.erb
<tr id="cakemodel_<%= cakemodel.id %>">
  <td>
    <div class="ratio ratio-1x1 rounded overflow-hidden" style="width: 60px;">
      <% if cakemodel.photo.attached? %>
        <%= cl_image_tag(cakemodel.photo.key, alt: cakemodel.name, fetch_format: :webp, class: 'w-100 h-100', style: 'object-fit: cover;', width: 120, crop: :fill) %>
      <% else %>
        <div class="bg-light d-flex align-items-center justify-content-center">
          <i class="fa-solid fa-image text-muted"></i>
        </div>
      <% end %>
    </div>
  </td>
  <td>
    <div class="d-flex flex-column">
      <span class="fw-semibold text-dark"><%= cakemodel.name %></span>
      <small class="text-muted"><%= cakemodel.slug %></small>
    </div>
  </td>
  <td>
    <span class="badge rounded-pill bg-light text-dark">
      <%= cakemodel.category.name %>
    </span>
  </td>
  <td>
    <span class="badge rounded-pill bg-info-subtle text-info-emphasis">
      <%= cakemodel.design.name %>
    </span>
  </td>
  <td>
    <% if cakemodel.featured_for_quick_order? %>
      <span class="badge rounded-pill bg-warning-subtle text-warning-emphasis">
        <i class="fa-solid fa-star me-1"></i>Homepage
      </span>
    <% else %>
      <span class="text-muted small">—</span>
    <% end %>
  </td>
  <td>
    <small class="text-muted" title="<%= l(cakemodel.updated_at, format: :long) %>">
      <%= time_ago_in_words(cakemodel.updated_at) %> în urmă
    </small>
  </td>
  <td class="text-end">
    <% modal_id = "editCakemodel#{cakemodel.id}" %>
    <div class="btn-group btn-group-sm" role="group">
      <%= link_to cakemodel_path(cakemodel), 
          class: 'btn btn-outline-primary', 
          title: 'Vezi/Editează',
          target: '_blank' do %>
        <i class="fa-solid fa-eye"></i>
      <% end %>
      <%= link_to '#',
          class: 'btn btn-outline-secondary',
          data: { bs_toggle: 'modal', bs_target: "##{modal_id}" },
          title: 'Editează' do %>
        <i class="fa-solid fa-pen"></i>
      <% end %>
      <%= link_to category_cakemodel_path(cakemodel.category, cakemodel), 
          method: :delete,
          data: { turbo_method: :delete, turbo_confirm: "Ștergi definitiv modelul '#{cakemodel.name}'?" },
          class: 'btn btn-outline-danger',
          title: 'Șterge' do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/dashboard/cakemodels/_edit_modal.html.erb
<div class="modal fade" id="<%= modal_id %>" tabindex="-1" aria-labelledby="<%= modal_id %>Label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="<%= modal_id %>Label">Modifică model tort</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', cakemodel: cakemodel, submit_label: 'Salvează modificările' %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/cakemodels/_modal.html.erb
<div class="modal fade" id="newCakemodelModal" tabindex="-1" aria-labelledby="newCakemodelModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="newCakemodelModalLabel">Adaugă model tort</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form', cakemodel: @cakemodel, submit_label: 'Adaugă model' %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/cakemodels/index.html.erb
<div class="container py-5 dashboard-cakemodels margin-top-20dvh">
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center mb-4 gap-3">
    <div>
      <span class="badge rounded-pill px-3 py-2 mb-2" style="background: #f1f5f9; color: #475569; font-weight: 600;">Administrator</span>
      <h1 class="h3 mb-0" style="color: #1e293b; font-weight: 600;">Administrare modele tort</h1>
      <p class="text-muted small mb-0">Gestionează modelele disponibile, marchează cele pentru comandă rapidă și verifică categorii.</p>
    </div>
    <div class="text-md-end">
      <div class="d-flex flex-column gap-2 align-items-md-end">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#newCakemodelModal">
          Adaugă model
        </button>
        <div>
          <p class="text-muted small mb-1">Modele în listă</p>
          <p class="h4 mb-0"><%= number_with_delimiter(@pagy&.count || 0) %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-md-2 row-cols-xl-4 g-3 mb-4">
    <% @stats_cards.each do |stat| %>
      <div class="col">
        <div class="card h-100" style="border: 1px solid #e5e7eb; border-radius: 8px;">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-start mb-3">
              <div>
                <p class="text-muted small mb-1"><%= stat[:label] %></p>
                <p class="h4 mb-0" style="color: #1e293b; font-weight: 700;"><%= number_with_delimiter(stat[:value]) %></p>
              </div>
              <span class="badge rounded-circle d-inline-flex align-items-center justify-content-center" style="width: 40px; height: 40px; background: #1e293b; color: white;">
                <i class="<%= stat[:icon] %>"></i>
              </span>
            </div>
            <p class="text-muted small mb-0"><%= stat[:hint] %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="card mb-4" style="border: 1px solid #e5e7eb; border-radius: 8px;">
    <div class="card-header py-3" style="background: #f8fafc; border-bottom: 1px solid #e5e7eb;">
      <h2 class="h6 mb-0" style="color: #1e293b; font-weight: 600;">Filtre rapide</h2>
    </div>
    <div class="card-body">
      <div class="d-flex flex-column flex-lg-row gap-3 align-items-lg-end">
        <%= form_with url: dashboard_cakemodels_path, method: :get, scope: :search, local: true, html: { class: 'row g-3 flex-grow-1 align-items-end' } do |f| %>
          <div class="col-12 col-lg-3">
            <%= f.label :search_for, 'Caută modele', class: 'form-label small text-uppercase text-muted fw-semibold' %>
            <%= f.search_field :search_for, value: @search_query, placeholder: 'Ex.: Tort Aniversar', class: 'form-control', aria: { label: 'Caută modele' } %>
          </div>
          <div class="col-12 col-lg-3">
            <%= f.label :category_id, 'Categorie', class: 'form-label small text-uppercase text-muted fw-semibold' %>
            <%= f.select :category_id,
                         options_for_select([['Toate categoriile', '']] + @categories.map { |category| [category.name, category.id] }, @selected_category),
                         {},
                         class: 'form-select' %>
          </div>
          <div class="col-12 col-lg-3">
            <%= f.label :design_id, 'Design', class: 'form-label small text-uppercase text-muted fw-semibold' %>
            <%= f.select :design_id,
                         options_for_select([['Toate design-urile', '']] + @designs.map { |design| [design.name, design.id] }, @selected_design),
                         {},
                         class: 'form-select' %>
          </div>
          <div class="col-12 col-lg-3">
            <div class="form-check mb-2">
              <%= f.check_box :featured, { class: 'form-check-input', include_hidden: false, checked: @filters[:featured] }, 'true', nil %>
              <%= f.label :featured, 'Doar pe homepage', class: 'form-check-label' %>
            </div>
            <%= f.submit 'Aplică filtrele', class: 'btn btn-primary w-100' %>
          </div>
        <% end %>

        <%= link_to 'Resetează filtrele', dashboard_cakemodels_path, class: "btn btn-outline-secondary#{@filters.blank? ? ' disabled' : ''}" %>
      </div>
    </div>
  </div>

  <div class="card shadow-sm border-0">
    <div class="card-header bg-white border-0 py-3 d-flex justify-content-between align-items-center flex-wrap gap-2">
      <h2 class="h6 mb-0"><%= @current_scope_label %></h2>
      <span class="badge bg-light text-dark"><%= pluralize(@pagy&.count || 0, 'înregistrare') %></span>
    </div>

    <% if @cakemodels.any? %>
      <div class="table-responsive">
        <table class="table table-sm align-middle mb-0">
          <thead class="table-light">
            <tr>
              <th style="width: 80px;">Imagine</th>
              <th>Denumire</th>
              <th>Categorie</th>
              <th>Design</th>
              <th>Status</th>
              <th>Actualizat</th>
              <th class="text-end">Acțiuni</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: 'cakemodel', collection: @cakemodels, as: :cakemodel %>
          </tbody>
        </table>
      </div>

      <div class="card-footer bg-white border-top py-3">
        <%== pagy_bootstrap_nav(@pagy) if @pagy %>
      </div>
    <% else %>
      <div class="card-body py-5 text-center">
        <i class="fa-solid fa-cake-candles fa-3x text-muted mb-3"></i>
        <p class="text-muted mb-3">Nu există modele care să corespundă criteriilor selectate.</p>
        <%= link_to 'Resetează filtrele', dashboard_cakemodels_path, class: 'btn btn-outline-primary' %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'modal' %>

<% @cakemodels.each do |cakemodel| %>
  <%= render 'edit_modal', cakemodel: cakemodel, modal_id: "editCakemodel#{cakemodel.id}" %>
<% end %>

<% if @cakemodel.errors.any? %>
  <script>
    (() => {
      const openNewCakemodelModal = () => {
        const modalElement = document.getElementById('newCakemodelModal');
        if (!modalElement) return;

        if (window.bootstrap && window.bootstrap.Modal) {
          const modal = window.bootstrap.Modal.getOrCreateInstance(modalElement);
          modal.show();
          return;
        }

        modalElement.classList.add('show');
        modalElement.style.display = 'block';
        modalElement.removeAttribute('aria-hidden');
        document.body.classList.add('modal-open');

        if (!document.querySelector('.modal-backdrop.show')) {
          const backdrop = document.createElement('div');
          backdrop.className = 'modal-backdrop fade show';
          document.body.appendChild(backdrop);
        }
      };

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', openNewCakemodelModal, { once: true });
      } else {
        openNewCakemodelModal();
      }
      document.addEventListener('turbo:load', openNewCakemodelModal, { once: true });
      window.addEventListener('load', openNewCakemodelModal, { once: true });
    })();
  </script>
<% end %>

<% if @edit_cakemodel_id.present? %>
  <script>
    (() => {
      const openEditCakemodelModal = () => {
        const modalElement = document.getElementById('editCakemodel<%= @edit_cakemodel_id %>');
        if (!modalElement) return;

        if (window.bootstrap && window.bootstrap.Modal) {
          const modal = window.bootstrap.Modal.getOrCreateInstance(modalElement);
          modal.show();
          return;
        }

        modalElement.classList.add('show');
        modalElement.style.display = 'block';
        modalElement.removeAttribute('aria-hidden');
        document.body.classList.add('modal-open');

        if (!document.querySelector('.modal-backdrop.show')) {
          const backdrop = document.createElement('div');
          backdrop.className = 'modal-backdrop fade show';
          document.body.appendChild(backdrop);
        }
      };

      if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', openEditCakemodelModal, { once: true });
      } else {
        openEditCakemodelModal();
      }
      document.addEventListener('turbo:load', openEditCakemodelModal, { once: true });
      window.addEventListener('load', openEditCakemodelModal, { once: true });
    })();
  </script>
<% end %>