config/routes.rb
Rails.application.routes.draw do
  resources :designs

  resources :categories do
    resources :recipes, except: %i[show]
    resources :cakemodels, except: %i[show]
    collection do
      get :recipes
    end
  end
  resources :recipes, only: %i[show] do
    resources :reviews, only: %i[create edit update destroy]
  end
  resources :cakemodels, only: %i[show] do
    resources :model_images, only: %i[new create destroy]
    resources :model_components, only: %i[new create destroy]
    resources :reviews, only: %i[create edit update destroy]
  end

  resources :model_components, only: %i[new create destroy]

  resources :features

  resources :items

  resource :cart, only: %i[show]

  devise_for :users
  root to: 'pages#home'
  get 'preturi', to: 'recipes#update_prices'
  patch 'preturi', to: 'recipes#bulk_update_prices'
  get 'cautare-retete', to: 'recipes#search'
  get 'how_to_order', to: 'pages#how_to_order'
  get 'about', to: 'pages#about'
  get 'valori-nutritionale', to: 'pages#valori_nutritionale'
  get 'gdpr', to: 'pages#gdpr', as: :gdpr
  get 'contul-meu', to: 'accounts#show', as: :account
  get 'dashboard',  to: 'pages#admin_dashboard'
  get 'dashboard/designs', to: 'designs#index'
  get 'dashboard/features', to: 'features#index'

  namespace :dashboard do
    resources :orders, only: %i[index show update destroy] do
      post :resend_emails, on: :member
    end
    resources :recipes, only: :index
    resources :cakemodels, only: %i[index create update]
    resources :delivery_dates, only: :index do
      collection do
        post :toggle
        post :block_range
      end
    end
    resources :users, only: %i[index edit update] do
      member do
        patch :toggle_admin
      end
    end

    resources :admin_users, controller: 'admin_users' do
      member do
        patch :toggle_admin
      end
    end

    resources :audit_logs, only: %i[index show] do
      collection do
        get :statistics
        get :export
      end
    end

    get 'analytics', to: 'analytics#index', as: 'analytics'
    
    namespace :design do
      get 'site_settings', to: 'site_settings#index'
      patch 'site_settings', to: 'site_settings#update'
      post 'site_settings/upload_hero_image', to: 'site_settings#upload_hero_image'
      delete 'site_settings/remove_hero_image', to: 'site_settings#remove_hero_image'
      post 'site_settings/templates', to: 'site_settings#create_template', as: 'create_site_setting_template'
      post 'site_settings/templates/:id/apply', to: 'site_settings#apply_template', as: 'apply_site_setting_template'
      delete 'site_settings/templates/:id', to: 'site_settings#destroy_template', as: 'destroy_site_setting_template'
    end
  end

  namespace :shop do
    resource :cart, only: :show
    resources :cart_items, only: %i[create update destroy]
    post 'checkout', to: 'checkout#create'
    get 'checkout/success', to: 'checkout#success'
    get 'checkout/cancel', to: 'checkout#cancel'
    get 'guest_confirmation/:id/:token', to: 'checkout#guest_confirmation', as: :guest_confirmation
  end

  # Catch-all route for 404 errors - must be last, but exclude Rails internal routes
  get '*any', to: 'errors#not_found', constraints: lambda { |req|
    req.path.exclude?('rails/active_storage') && 
    req.path.exclude?('rails/conductor')
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_one_attached :photo
  has_many :recipes, dependent: :destroy
  has_many :cakemodels, dependent: :destroy
  has_many :designs, dependent: :destroy
  validates :name, presence: true
  # validates :photo, presence: true
  after_save :slugify, unless: :check_slug
  include SlugHelper

  def to_param
    "#{slug}"
  end

  def menu_like?
    return false unless has_attribute?(:menu_like)

    self[:menu_like]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def new
    @category = Category.new
    authorize @category
    @page_title = 'Creează o nouă categorie || Cofetăria Irina - Bacău'
  end

  def create
   @category = Category.new(category_params)
   authorize @category
   if @category.save
    redirect_to categories_path, notice: 'Category was successfully created.'
   else
    render :new
   end
  end

  def index
    @categories = policy_scope(Category).order('id ASC').includes([photo_attachment: :blob])
    @page_title = 'Categorii de produse || Cofetăria Irina - Bacau'
  end

  def show
    @recipes = @category.recipes.order("name ASC")
    @cakemodels = @category.cakemodels
    @page_title = "Rețete de #{@category.name.downcase} ・ Cofetăria Irina"
    @page_main_title = @category.name
  end

  def edit
    @page_title = 'Modifică categoria || Cofetăria Irina - Bacău'
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def category_params
    permitted = [:name, :photo, :has_recipe, :has_models, :slug, :description]
    permitted << :menu_like if Category.column_names.include?('menu_like')
    params.require(:category).permit(*permitted)
  end

  def set_category
    @category = authorize Category.find_by(slug: params[:id])
  end

end

app/views/categories/_category.html.erb
<div class="category-card">
  <div class='category-card__photo' style="background-image: url('<%= cl_image_path(category.photo.key) %>');"></div>
  <div class="category-card__info">
    <h2><%= category.name %></h2>
    <p><%= category.description %></p>
    <% cat_link = category.has_models && !category.has_recipe ? category_cakemodels_path(category) : category_recipes_path(category) %>
    <%= link_to 'Vezi mai multe', cat_link, class: 'category-card__button' %>
  </div>
  <% if policy(category).edit? || policy(category).destroy? %>
    <div class="card-crud">
      <% if policy(category).edit? %>
        <%= link_to edit_category_path(category), class: '' do %>
        <i class="far fa-edit"></i>
        <% end %>
      <% end %>
      <% if policy(category).destroy? %>
        <%= link_to category_path(category), class: '', data: { turbo_method: :delete, turbo_confirm: "Ești sigur că vrei să-l ștergi pe ?"} do %>
        <i class="fas fa-trash-alt"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>











<!-- former card -->


<!-- <div class='card-container' style="background-image: url('<%= cl_image_path(category.photo.key) %>');" data-controller="general" data-general-target="container" data-action="mouseenter->general#show mouseleave->general#hide">
  <% cat_link = category.has_models && !category.has_recipe ? category_cakemodels_path(category) : category_recipes_path(category) %>
  <%= link_to cat_link, class: 'card-paths-link' do %>
    <h3 data-general-target="title" class="card-title-h3"><%= category.name %></h3>
    <% end %>
</div> -->

app/views/categories/edit.html.erb
<%= render 'partials/form_new_category' %>

app/views/categories/index.html.erb
<div class="cards-main-container categories-index">
  <%=render @categories %>
</div>
<div class="card-index-new">
  <% if policy(Category).new? %>
    <%= link_to 'Categorie nouă', new_category_path, class: 'btn-default' %>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'partials/form_new_category' %>

app/views/categories/show.html.erb
<div class="container-fluid py-5">
  <div class="row mx-1 pt-5">
    <div class="col pt-5">
      <div class="d-flex flex-wrap justify-content-center ">
        <!-- <p class="first-margin-bottom"></p>
          <%= render 'partials/categories/render_sections' %>
        <p class="last-margin-bottom d-inline"></p> -->
        <%= render 'partials/categories/recipe' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>